### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by liuetengsheng** [nbd-wtf/go-nostr#76]
Always send in a loop, Concurrent errors may occur, Causing program interruption
if len(relayConnect) != 2 {
		for _, url := range []string{"wss://relay.damus.io", "wss://nos.lol"} {
			relay, e := nostr.RelayConnect(context.Background(), url)
			if e != nil {
				fmt.Println(e)
				delete(relayConnect, url)
				continue
			}
			relayConnect[url] = relay
		}
	}

for url, relay := range relayConnect {
		var a context.Context = context.Background()
		b, e := relay.Publish(a, ev)
		fmt.Println("published to ", url, b, e)

		if e != nil {
			fmt.Println(e)
			delete(relayConnect, url)
}

panic: concurrent write to websocket connection

goroutine 241620 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00e0e9e60, 0x1, {0x0?, 0x0?, 0x0?})
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:610 +0x50b
github.com/gorilla/websocket.(*messageWriter).Close(0xc01275ce10?)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:724 +0x45
github.com/gorilla/websocket.(*Conn).beginMessage(0xc0000a09a0, 0xc01275ce10, 0x1)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:473 +0x42
github.com/gorilla/websocket.(*Conn).NextWriter(0xc0000a09a0, 0x1)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:513 +0x45
github.com/gorilla/websocket.(*Conn).WriteJSON(0x7f40fc119418?, {0xa72a80, 0xc0044c30e0})
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/json.go:24 +0x45
github.com/nbd-wtf/go-nostr.(*Connection).WriteJSON(0xc0044fe2e0?, {0xa72a80?, 0xc0044c30e0?})
	/root/go/pkg/mod/github.com/nbd-wtf/go-nostr@v0.15.3/connection.go:22 +0xb0
github.com/nbd-wtf/go-nostr.(*Subscription).Unsub(0xc014007a00)
	/root/go/pkg/mod/github.com/nbd-wtf/go-nostr@v0.15.3/subscription.go:48 +0x165
github.com/nbd-wtf/go-nostr.(*Subscription).Fire.func1()
	/root/go/pkg/mod/github.com/nbd-wtf/go-nostr@v0.15.3/subscription.go:79 +0x3c
created by github.com/nbd-wtf/go-nostr.(*Subscription).Fire
	/root/go/pkg/mod/github.com/nbd-wtf/go-nostr@v0.15.3/subscription.go:77 +0x2fc

**Comment by fiatjaf** [comment]
What version?

**Comment by liuetengsheng** [comment]
> 什么版本？

Use first v0.15.3 , Upgrade to v0.16.0, The same problem has also arisen @fiatjaf

**Comment by fiatjaf** [comment]
Hmm, there is a mutex around every connection write, I don't understand why this happens. I need some help here.

**Comment by pbennett** [comment]
Probably unrelated but I noticed that Relay.Connect creates its own context and cancel() that is exclusive to that method.
However, if relay.Close() is called, then the context isn't closed and Relay.Connect() (which is "the" event handler code - isn't cancelled) - yet is now working with a a closed websocket connection.
I suspect there are other similar gotchas like this at work here.

**Comment by andyleap** [comment]
https://github.com/nbd-wtf/go-nostr/blob/b077a41f83ac66b064cd90441d45685314e19a11/relay.go#L122 doesn't use the mutex?
